services:
  - type: web
    name: reportaya-backend
    runtime: docker
    repo: https://github.com/jeffangeloss/ReportaYA-Backend.git
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: none
      - key: JWT_SECRET
        generateValue: true
      - key: APP_BASE_URL
        sync: false
      - key: APP_PASSWORD_RESET_URL
        value: reportaya://reset-password
